### ISSUE TITLE
sudo -v causes problems in EC2 ubuntu

### ISSUE THREAD

**Issue by cancan101** [seanbell/opensurfaces#1]
```
$ sudo -v
[sudo] password for ubuntu: 
```

but no password will make it happy.

**Comment by seanbell** [comment]
Thanks for pointing this out -- `sudo -v` just increases the timeout, and isn't necessary.  I removed it (https://github.com/seanbell/opensurfaces/commit/c316e1ba3448154a47d2a9a20acb43632dcbbede)
